version: '3.3'
services:
    cogentapps:
        container_name: chat-with-gpt
        volumes:
            - '/srv/mergerfs/maindrive/AppData/chat-with-gpt/data:/app/data'
        ports:
            - '8015:3000'
        image: techkev/chat-with-gpt
        restart: always